# Generated by Django 4.0.2 on 2022-02-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('phoneContact', models.PositiveIntegerField(max_length=25)),
                ('nameContact', models.CharField(max_length=100)),
                ('adressCom', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOrder', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('todo', models.TextField(max_length=1000)),
                ('status', models.PositiveSmallIntegerField(max_length=1)),
                ('docFile', models.CharField(max_length=200)),
                ('crataedBy', models.IntegerField(max_length=11)),
                ('assignTo', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
    ]
